from apps.customers.tenants.api.views import *
from apps.customers.tenants.api.plan_views import *
from apps.gestionDeUsuarioySeguridad.cu3_gestion_de_usuario.api.views import *
from apps.gestionDeUsuarioySeguridad.cu4_gestion_de_roles.api.rol_views import *
from apps.gestionDeUsuarioySeguridad.cu5_gestionar_permisos.api.permiso_views import *
from apps.gestionDeUsuarioySeguridad.cu3_gestion_de_usuario.api.device_token_views import *
from apps.customers.clientes.api.views import *
from apps.gestionDeUsuarioySeguridad.cu6_gestionar_bitacora.api.bitacora_views import *
from apps.gestionDeUsuarioySeguridad.cu6_gestionar_bitacora.api.respaldo_views import *