@startuml
left to right direction
skinparam BackgroundColor white

actor "Cliente" as Cliente
boundary "catalogoForm" as Form
control "reservaControl" as Control
database "Reserva" as DB

Cliente -> Form : 1: seleccionarPreventa()\n2: pagarReserva()
Form -> Control : 1.1: verificarPreventa()\n2.1: procesarPago()
Control -> DB : 2.2: registrarReserva()
@enduml
