# Generated by Django 5.2.12 on 2026-05-08 00:49

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('fecha_inicio_suscripcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Suscripción')),
                ('fecha_fin_suscripcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin de Suscripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Comercial de la Tienda')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Tienda')),
                ('categoria_tienda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría de la Tienda')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del Logo de la Tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=40, null=True, verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIT (Número de Identificación Tributaria)')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'customers_cliente',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mensual')),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Anual')),
                ('max_usuarios', models.IntegerField(verbose_name='Máximo de Usuarios')),
                ('max_productos', models.IntegerField(verbose_name='Máximo de Productos')),
                ('facturacion_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Límite de Facturación Mensual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'db_table': 'customers_plan',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RespaldoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('blob_data', models.BinaryField(help_text='Datos del respaldo comprimidos y ofuscados')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict, help_text='Información técnica del respaldo')),
            ],
            options={
                'verbose_name': 'Respaldo del Sistema',
                'verbose_name_plural': 'Respaldos del Sistema',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'VENDEDOR'), (3, 'CLIENTE'), (4, 'VIEWER')], default=4, verbose_name='Nivel de Permisos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'customers_rol',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='customers.client')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='customers.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo')),
                ('metadatos', models.JSONField(blank=True, null=True, verbose_name='Metadatos')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'customers_bitacora',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='customers.plan', verbose_name='Plan de Suscripción'),
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Ciclo de Facturación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suscripciones', to='customers.plan', verbose_name='Plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='customers.client', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'customers_suscripcion',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
