# Generated by Django 5.2.12 on 2026-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/iconos/', verbose_name='Icono de la Tienda'),
        ),
    ]
