# Generated by Django 5.2.12 on 2026-05-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='categoria_tienda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría de la Tienda'),
        ),
        migrations.AddField(
            model_name='client',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Tienda'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Logo de la Tienda'),
        ),
        migrations.AddField(
            model_name='client',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Comercial de la Tienda'),
        ),
    ]
