# Generated by Django 5.2.12 on 2026-05-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_configuracionrespaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='es_basico',
            field=models.BooleanField(default=False, help_text='Indica si este permiso está disponible para todas las tiendas sin importar su plan.', verbose_name='Permiso Básico (Todos los planes)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='permisos',
            field=models.ManyToManyField(blank=True, help_text='Funcionalidades (permisos premium) que desbloquea este plan.', related_name='planes', to='customers.permiso', verbose_name='Permisos Incluidos'),
        ),
    ]
