# Generated by Django 5.2.12 on 2026-05-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_permiso_es_basico_plan_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre del Rol'),
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('nombre', 'tenant'), name='unique_rol_nombre_per_tenant'),
        ),
    ]
