# Generated by Django 5.2.12 on 2026-06-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_mobilerelease'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS customers_configuracion_respaldo CASCADE;",
                    reverse_sql=""
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS customers_respaldo CASCADE;",
                    reverse_sql=""
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='ConfiguracionRespaldo',
                ),
                migrations.DeleteModel(
                    name='RespaldoSistema',
                ),
            ]
        )
    ]
