# Generated by Django 5.2.12 on 2026-06-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_delete_configuracionrespaldo_delete_respaldosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='limite_alcanzado_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Límite Alcanzado'),
        ),
        migrations.AddField(
            model_name='plan',
            name='ventas_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Límite de Ventas Diarias'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='facturacion_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Límite de Facturación Diaria'),
        ),
    ]
