# Generated by Django 5.2.12 on 2026-05-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_negocio', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='customers.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_negocio.carrito', verbose_name='Carrito'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='app_negocio.categoria', verbose_name='Categoría Principal'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas', to='customers.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_negocio.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='app_negocio.carrito', verbose_name='Carrito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='factura', to='app_negocio.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='app_negocio.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='en_facturas', to='app_negocio.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='app_negocio.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_negocio.promocion', verbose_name='Promoción'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='app_negocio.tipopago', verbose_name='Tipo de Pago'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('nombre', 'parent'), name='unique_categoria_por_padre'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'producto')},
        ),
    ]
