# Generated by Django 5.2.12 on 2026-05-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_negocio', '0003_producto_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Atributos (Color, Talla, etc.)'),
        ),
    ]
