# Generated by Django 5.2.12 on 2026-05-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_negocio', '0004_producto_atributos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Session ID'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PROCESADO', 'Procesado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
    ]
