# Generated by Django 5.2.12 on 2026-06-20 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('PAGO', 'Pago'), ('PROMOCION', 'Promoción')], default='TAREA', max_length=20, verbose_name='Tipo')),
                ('fecha_recordatorio', models.DateTimeField(verbose_name='Fecha y Hora del Evento')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios', to='cu13_gestionar_estado_de_pedido.pedido', verbose_name='Pedido vinculado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'app_negocio_recordatorio',
                'ordering': ['fecha_recordatorio'],
            },
        ),
    ]
