# Generated by Django 5.2.12 on 2026-07-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cu13_gestionar_estado_de_pedido", "0002_pedido_envio"),
        ("cu20_gestionar_recordatorios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordatorio",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordatorios",
                to="cu13_gestionar_estado_de_pedido.pedido",
                verbose_name="Pedido vinculado",
            ),
        ),
    ]
