# Generated by Django 5.2.12 on 2026-06-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0010_delete_configuracionrespaldo_delete_respaldosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='DIARIO', max_length=10)),
                ('hora_ejecucion', models.TimeField(help_text='Hora del día (HH:MM:SS)')),
                ('dia_referencia', models.IntegerField(default=0, help_text='Día de la semana (0-6) o del mes (1-31)')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuraciones de Respaldo',
                'db_table': 'customers_configuracion_respaldo',
            },
        ),
        migrations.CreateModel(
            name='RespaldoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_path', models.CharField(blank=True, help_text='Ruta física en el servidor', max_length=255, null=True)),
                ('blob_data', models.BinaryField(blank=True, help_text='Copia de seguridad en DB (opcional)', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Info técnica: tablas, tamaño, etc.')),
                ('anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesor', to='cu21_generar_backup.respaldosistema', verbose_name='Versión Anterior (Cola)')),
                ('siguiente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecesor', to='cu21_generar_backup.respaldosistema', verbose_name='Versión Siguiente')),
            ],
            options={
                'verbose_name': 'Respaldo del Sistema',
                'verbose_name_plural': 'Respaldos del Sistema',
                'db_table': 'customers_respaldo',
                'ordering': ['timestamp'],
            },
        ),
    ]
